import type { AgentProfile } from "@/types/agent";

export const mockAgents: AgentProfile[] = [
  {
    id: "agent-1",
    name: "Jean-Paul Nkurunziza",
    initials: "JP",
    avatarColor: "from-amnii-navy to-amnii-navy/70",
    servesIn: ["Remera", "Kimironko", "Kacyiru"],
    district: "gasabo",
    languages: ["Kinyarwanda", "English", "French"],
    rentCount: 18,
    saleCount: 6,
    reviewCount: 24,
    agency: "Kigali Prime Realty",
    agencyShort: "KPR",
    rating: 4.9,
    responseTime: "1h",
    phoneVerified: true,
    badges: ["trusted_commissioner", "quick_responder"],
    whatsapp: "+250788100001",
  },
  {
    id: "agent-2",
    name: "Marie Claire Uwase",
    initials: "MC",
    avatarColor: "from-rw-green to-rw-green/70",
    servesIn: ["Niboye", "Gatenga", "Kagarama"],
    district: "kicukiro",
    languages: ["Kinyarwanda", "English"],
    rentCount: 14,
    saleCount: 3,
    reviewCount: 11,
    agency: "Green Hills Properties",
    agencyShort: "GHP",
    rating: 4.7,
    responseTime: "2h",
    phoneVerified: true,
    badges: ["trusted_commissioner", "quality_lister"],
    whatsapp: "+250788100002",
  },
  {
    id: "agent-3",
    name: "Patrick Niyonzima",
    initials: "PN",
    avatarColor: "from-rw-yellow to-amber-400",
    servesIn: ["Nyamirambo", "Muhima", "Biryogo"],
    district: "nyarugenge",
    languages: ["Kinyarwanda", "English", "French"],
    rentCount: 22,
    saleCount: 9,
    reviewCount: 31,
    agency: "City Centre Estates",
    agencyShort: "CCE",
    rating: 4.8,
    responseTime: "45m",
    phoneVerified: true,
    badges: ["trusted_commissioner", "quality_lister", "quick_responder"],
    whatsapp: "+250788100003",
  },
  {
    id: "agent-4",
    name: "Grace Ingabire",
    initials: "GI",
    avatarColor: "from-sky-500 to-rw-blue",
    servesIn: ["Remera", "Kacyiru"],
    district: "gasabo",
    languages: ["Kinyarwanda", "English"],
    rentCount: 11,
    saleCount: 2,
    reviewCount: 7,
    agency: "Amahoro Housing",
    agencyShort: "AH",
    rating: 4.6,
    responseTime: "3h",
    phoneVerified: true,
    badges: ["quality_lister"],
    whatsapp: "+250788100004",
  },
  {
    id: "agent-5",
    name: "Emmanuel Habimana",
    initials: "EH",
    avatarColor: "from-emerald-600 to-rw-green",
    servesIn: ["Kimironko", "Remera", "Kacyiru"],
    district: "gasabo",
    languages: ["Kinyarwanda", "English", "French"],
    rentCount: 9,
    saleCount: 5,
    reviewCount: 9,
    agency: "Eastview Realty",
    agencyShort: "EVR",
    rating: 4.5,
    responseTime: "2h",
    phoneVerified: true,
    badges: ["quick_responder"],
    whatsapp: "+250788100005",
  },
  {
    id: "agent-6",
    name: "Alice Mukamana",
    initials: "AM",
    avatarColor: "from-violet-500 to-rw-blue",
    servesIn: ["Gatenga", "Niboye"],
    district: "kicukiro",
    languages: ["Kinyarwanda", "English"],
    rentCount: 16,
    saleCount: 4,
    reviewCount: 15,
    agency: "Kicukiro Homes",
    agencyShort: "KH",
    rating: 4.8,
    responseTime: "1.5h",
    phoneVerified: true,
    badges: ["trusted_commissioner"],
    whatsapp: "+250788100006",
  },
];

export const AGENT_DISTRICT_TABS = [
  { id: "all", label: "All Kigali" },
  { id: "gasabo", label: "Gasabo" },
  { id: "kicukiro", label: "Kicukiro" },
  { id: "nyarugenge", label: "Nyarugenge" },
] as const;
