import type { Listing } from "@/types";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Modern Villa in Kacyiru",
    description: "Executive 4-bedroom villa with garden, security, and parking near Amahoro Stadium.",
    propertyType: "house",
    listingType: "rent",
    price: 2500000,
    currency: "RWF",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    squareMeters: 320,
    district: "Gasabo",
    sector: "Kacyiru",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100001",
    whatsappNumber: "+250788100001",
    features: ["garden", "security", "parking"],
    status: "active",
    verificationStatus: "verified",
    ownerId: "owner-1",
    listingSource: "owner_direct",
    agentId: null,
    contactDisplay: "owner",
    agentName: null,
    agentPhone: null,
    agentWhatsapp: null,
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Luxury Apartment Remera",
    description: "Bright 2BR apartment with balcony, 24/7 security, near Amahoro Stadium.",
    propertyType: "apartment",
    listingType: "rent",
    price: 850000,
    currency: "RWF",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    squareMeters: 95,
    district: "Gasabo",
    sector: "Remera",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100002",
    whatsappNumber: "+250788100002",
    features: ["security", "parking", "balcony"],
    status: "active",
    verificationStatus: "verified",
    ownerId: "owner-2",
    listingSource: "agent_managed",
    agentId: "agent-1",
    contactDisplay: "agent",
    agentName: "Jean-Paul Nkurunziza",
    agentPhone: "+250788100001",
    agentWhatsapp: "+250788100001",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Family House Niboye",
    description: "Spacious 4-bedroom house with garden in quiet Kicukiro neighborhood.",
    propertyType: "house",
    listingType: "sale",
    price: 185000000,
    currency: "RWF",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    squareMeters: 220,
    district: "Kicukiro",
    sector: "Niboye",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100003",
    whatsappNumber: null,
    features: ["garden", "parking"],
    status: "active",
    verificationStatus: "verified",
    ownerId: "owner-3",
    listingSource: "owner_direct",
    agentId: null,
    contactDisplay: "owner",
    agentName: null,
    agentPhone: null,
    agentWhatsapp: null,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Kacyiru Studio",
    description: "Compact furnished studio ideal for professionals.",
    propertyType: "studio",
    listingType: "rent",
    price: 300000,
    currency: "RWF",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    squareMeters: 42,
    district: "Gasabo",
    sector: "Kacyiru",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100004",
    whatsappNumber: "+250788100004",
    features: ["furnished", "wifi"],
    status: "active",
    verificationStatus: "unverified",
    ownerId: "owner-4",
    listingSource: "owner_direct",
    agentId: null,
    contactDisplay: "owner",
    agentName: null,
    agentPhone: null,
    agentWhatsapp: null,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Office Nyamirambo",
    description: "Central business district office with meeting room access.",
    propertyType: "office",
    listingType: "commercial_rent",
    price: 1200000,
    currency: "RWF",
    bedrooms: null,
    bathrooms: 2,
    parkingSpaces: 3,
    squareMeters: 150,
    district: "Nyarugenge",
    sector: "Nyamirambo",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100005",
    whatsappNumber: "+250788100005",
    features: ["elevator", "security"],
    status: "active",
    verificationStatus: "verified",
    ownerId: "owner-5",
    listingSource: "agent_managed",
    agentId: "agent-2",
    contactDisplay: "agent",
    agentName: "Marie Claire Uwase",
    agentPhone: "+250788100002",
    agentWhatsapp: "+250788100002",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Kimironko Room",
    description: "Affordable single room with shared kitchen, close to market.",
    propertyType: "room",
    listingType: "rent",
    price: 120000,
    currency: "RWF",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    squareMeters: 18,
    district: "Gasabo",
    sector: "Kimironko",
    cell: null,
    latitude: null,
    longitude: null,
    contactPhone: "+250788100006",
    whatsappNumber: "+250788100006",
    features: ["water", "electricity"],
    status: "active",
    verificationStatus: "unverified",
    ownerId: "owner-6",
    listingSource: "owner_direct",
    agentId: null,
    contactDisplay: "owner",
    agentName: null,
    agentPhone: null,
    agentWhatsapp: null,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const urgentListings = mockListings.slice(0, 3).map((l, i) => ({
  ...l,
  urgent: i === 0,
  isNew: i === 1,
}));
